### ISSUE TITLE
Automatic country selection based on geolocation

### ISSUE THREAD

**Issue by bence-toth** [bence-toth/covid-charts#11]

**Comment by bancho22** [comment]
I think it would be nice to replace the initial data that shows up about the two default countries with data comparing the country in which you're currently located (should still fallback to something) with worldwide data, so that you can see how well your country is doing in relation to the global situation.

Unfortunately, I struggled a lot trying to find an API to supply the worldwide data. The best I found was this `https://corona.lmao.ninja/v2/historical/all` and it only goes a month back.

**Comment by bancho22** [comment]
There it is ;)

`https://covid.ourworldindata.org/data/owid-covid-data.json`

**Comment by bence-toth** [comment]
> PS: This will require a backend.

I'm actually considering that I'd create static data and host it in this repo, and have GitHub Actions update it every day. That way the app would be a lot faster, and we wouldn't have to worry about rate limiting etc.
